//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_RRHHEntities : DbContext
    {
        public DB_RRHHEntities()
            : base("name=DB_RRHHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<area> areas { get; set; }
        public virtual DbSet<empleado_empleo> empleado_empleo { get; set; }
        public virtual DbSet<empleado1> empleado1 { get; set; }
        public virtual DbSet<empleo1> empleo1 { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
