//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary2
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado_empleo
    {
        public int empleado_empleo1 { get; set; }
        public int codigo_empleo { get; set; }
        public int codigo_area { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_final { get; set; }
        public bool activo { get; set; }
    
        public virtual area area { get; set; }
        public virtual empleado1 empleado1 { get; set; }
        public virtual empleo1 empleo1 { get; set; }
    }
}
